version: '3.8'
services:
  web:
    container_name: tunify-web
    build:
      context: .
      target: tunify-web
    volumes:
        - .:/code
    links:
      - php
    networks:
      - reverse
  php:
      build:
        context: .
        target: tunify-php
      container_name: tunify-php
      volumes:
        - .:/code

  mysql:
    image: mysql:latest
    container_name: tunify-db
    environment:
      MYSQL_ROOT_PASSWORD: tunify
      MYSQL_DATABASE: dbName
      MYSQL_USER: dbUser
      MYSQL_PASSWORD: tunify
    volumes:
      - db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: tunify-phpmyadmin
    links:
      - mysql:db
    ports:
      - "8082:80"
    environment:
      - PMA_USER=root
      - PMA_PASSWORD=tunify
      - PHP_UPLOAD_MAX_FILESIZE=100MB

networks:
  reverse:
    name: reverse_default
  tunify:
    name: tunify_default

volumes:
  db:
